// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

namespace CrudKARYAWAN.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext)), Migration("20231016151307_initialsetup")]
    internal abstract class initialsetupBase
    {
        protected abstract override void BuildTargetModel(ModelBuilder modelBuilder);
    }
}